class AddSubjectToUser < ActiveRecord::Migration
  def up
    add_column :users, :subject, :string

    Asker.where(id: 18).first.try(:update, {subject: 'Biology'})
    Asker.where(id: 32584).first.try(:update, {subject: 'Art History'})
    Asker.where(id: 35127).first.try(:update, {subject: 'Immune System'})
    Asker.where(id: 10567).first.try(:update, {subject: 'Hunger Games'})
    Asker.where(id: 36144).first.try(:update, {subject: 'Constitutional Law'})
    Asker.where(id: 54893).first.try(:update, {subject: 'World War II'})
    Asker.where(id: 35213).first.try(:update, {subject: 'Genetics'})
    Asker.where(id: 108).first.try(:update, {subject: 'Psychology'})
    Asker.where(id: 35685).first.try(:update, {subject: 'French Revolution'})
    Asker.where(id: 35448).first.try(:update, {subject: 'Stereochemistry'})
    Asker.where(id: 8367).first.try(:update, {subject: 'Geography'})
    Asker.where(id: 35459).first.try(:update, {subject: 'Spanish Subjunctive'})
    Asker.where(id: 27857).first.try(:update, {subject: 'Physics'})
    Asker.where(id: 12640).first.try(:update, {subject: 'SAT Math'})
    Asker.where(id: 13588).first.try(:update, {subject: 'Beginner Spanish'})
    Asker.where(id: 66).first.try(:update, {subject: 'US Presidents'})
    Asker.where(id: 34534).first.try(:update, {subject: 'World Capitals'})
    Asker.where(id: 231).first.try(:update, {subject: 'History'})
    Asker.where(id: 223).first.try(:update, {subject: 'Marketing'})
    Asker.where(id: 35106).first.try(:update, {subject: 'Respiratory System'})
    Asker.where(id: 36605).first.try(:update, {subject: 'American Revolutionary War'})
    Asker.where(id: 284).first.try(:update, {subject: 'Football'})
    Asker.where(id: 322).first.try(:update, {subject: 'Economics'})
    Asker.where(id: 22).first.try(:update, {subject: 'Cycling'})
    Asker.where(id: 31).first.try(:update, {subject: 'Organic Chemistry'})
    Asker.where(id: 34963).first.try(:update, {subject: 'Logarithms'})
    Asker.where(id: 32575).first.try(:update, {subject: 'Photosynthesis'})
    Asker.where(id: 227).first.try(:update, {subject: 'SAT Vocab'})
    Asker.where(id: 325).first.try(:update, {subject: 'AP US History'})
    Asker.where(id: 10572).first.try(:update, {subject: 'Twilight'})
    Asker.where(id: 19454).first.try(:update, {subject: 'SAT Numbers'})
    Asker.where(id: 308).first.try(:update, {subject: 'Spanish Verbs'})
    Asker.where(id: 9217).first.try(:update, {subject: 'LSAT'})
    Asker.where(id: 34905).first.try(:update, {subject: 'Plant Growth'})
    Asker.where(id: 191).first.try(:update, {subject: 'Philosophy'})
    Asker.where(id: 28064).first.try(:update, {subject: 'Hematology'})
    Asker.where(id: 324).first.try(:update, {subject: 'US Capitals'})
    Asker.where(id: 326).first.try(:update, {subject: 'Anatomy'})
    Asker.where(id: 10565).first.try(:update, {subject: 'Harry Potter and the Prisoner of Azkaban'})
    Asker.where(id: 374).first.try(:update, {subject: 'Beer'})
    Asker.where(id: 8373).first.try(:update, {subject: 'Thailand'})
    Asker.where(id: 10573).first.try(:update, {subject: 'The Hobbit'})
    Asker.where(id: 54892).first.try(:update, {subject: 'Cardiology'})
    Asker.where(id: 7362).first.try(:update, {subject: 'Weather'})
    Asker.where(id: 24740).first.try(:update, {subject: 'SAT Geometry'})
    Asker.where(id: 19).first.try(:update, {subject: 'Chemistry'})
    Asker.where(id: 12982).first.try(:update, {subject: 'Intermediate Spanish'})
    Asker.where(id: 34662).first.try(:update, {subject: 'Lower Limb System'})
    Asker.where(id: 14106).first.try(:update, {subject: 'SAT Algebra'})
    Asker.where(id: 26070).first.try(:update, {subject: 'NREMT'})
    Asker.where(id: 34320).first.try(:update, {subject: 'Dermotomes and Myotomes'})
    Asker.where(id: 26522).first.try(:update, {subject: 'Veterinary Medicine'})
    Asker.where(id: 34530).first.try(:update, {subject: 'MCAT Biology'})
  end

  def down
    remove_column :users, :subject, :string
  end
end
