class AddSubjectToUser < ActiveRecord::Migration
  def up
    add_column :users, :subject, :string

    Asker.find(18).update subject: 'Biology'
    Asker.find(32584).update subject: 'Art History'
    Asker.find(35127).update subject: 'Immune System'
    Asker.find(10567).update subject: 'Hunger Games'
    Asker.find(36144).update subject: 'Constitutional Law'
    Asker.find(54893).update subject: 'World War II'
    Asker.find(35213).update subject: 'Genetics'
    Asker.find(108).update subject: 'Psychology'
    Asker.find(35685).update subject: 'French Revolution'
    Asker.find(35448).update subject: 'Stereochemistry'
    Asker.find(8367).update subject: 'Geography'
    Asker.find(35459).update subject: 'Spanish Subjunctive'
    Asker.find(27857).update subject: 'Physics'
    Asker.find(12640).update subject: 'SAT Math'
    Asker.find(13588).update subject: 'Beginner Spanish'
    Asker.find(66).update subject: 'US Presidents'
    Asker.find(34534).update subject: 'World Capitals'
    Asker.find(231).update subject: 'History'
    Asker.find(223).update subject: 'Marketing'
    Asker.find(35106).update subject: 'Respiratory System'
    Asker.find(36605).update subject: 'American Revolutionary War'
    Asker.find(284).update subject: 'Football'
    Asker.find(322).update subject: 'Economics'
    Asker.find(22).update subject: 'Cycling'
    Asker.find(31).update subject: 'Organic Chemistry'
    Asker.find(34963).update subject: 'Logarithms'
    Asker.find(32575).update subject: 'Photosynthesis'
    Asker.find(227).update subject: 'SAT Vocab'
    Asker.find(325).update subject: 'AP US History'
    Asker.find(10572).update subject: 'Twilight'
    Asker.find(19454).update subject: 'SAT Numbers'
    Asker.find(308).update subject: 'Spanish Verbs'
    Asker.find(9217).update subject: 'LSAT'
    Asker.find(34905).update subject: 'Plant Growth'
    Asker.find(191).update subject: 'Philosophy'
    Asker.find(28064).update subject: 'Hematology'
    Asker.find(324).update subject: 'US Capitals'
    Asker.find(326).update subject: 'Anatomy'
    Asker.find(10565).update subject: 'Harry Potter and the Prisoner of Azkaban'
    Asker.find(374).update subject: 'Beer'
    Asker.find(8373).update subject: 'Thailand'
    Asker.find(10573).update subject: 'The Hobbit'
    Asker.find(54892).update subject: 'Cardiology'
    Asker.find(7362).update subject: 'Weather'
    Asker.find(24740).update subject: 'SAT Geometry'
    Asker.find(19).update subject: 'Chemistry'
    Asker.find(12982).update subject: 'Intermediate Spanish'
    Asker.find(34662).update subject: 'Lower Limb System'
    Asker.find(14106).update subject: 'SAT Algebra'
    Asker.find(26070).update subject: 'NREMT'
    Asker.find(34320).update subject: 'Dermotomes and Myotomes'
    Asker.find(26522).update subject: 'Veterinary Medicine'
    Asker.find(34530).update subject: 'MCAT Biology'
  end

  def down
    remove_column :users, :subject, :string
  end
end
